### ISSUE TITLE
Sintesis

### ISSUE THREAD

**Issue by ElisabetRD** [SistemasTecTlaxiaco/actividad-3-sintesis-ElisabetRD#2]
[Sintesis_BuenasPracticas.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-ElisabetRD/files/12542003/Sintesis_BuenasPracticas.pdf)

**Comment by Aricel117** [comment]
Calif: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
